timescale/tobs

- chart/Chart.yaml
- chart/templates/NOTES.txt
- chart/templates/configmap-prometheus.yaml
- chart/templates/secret-grafana-datasources.yaml
- chart/values.yaml
The stable/grafana subchart is added as a dependency
to be deployed. If the Prometheus server or TimescaleDB are
enabled they will be added as a provisioned data sources.
> Add Grafana

- README.md
- chart/templates/NOTES.txt
- chart/templates/secret-grafana-datasources.yaml
- chart/values.yaml
Previous configuration of provisioned data-sources would only work
for the case where prometheus and timescaledb were deployed within
the same release with this chart. This way they chart can support
grafana creating provisioned data sources for a timescaledb or
prometheus instance deployed or managed separately.
> Modify provisioned data-sources values to support external deploys

- chart/dashboards/k8s-cluster.json
- chart/dashboards/k8s-hardware.json
- chart/values.yaml
This PR adds a cluster status dashboard giving information about the deployments, nodes, pods, and containers for a given Kubernetes cluster and makes minor refinements to the hardware status dashboard.
> Add cluster status and refine hardware status dashboards

- README.md
- chart/Chart.yaml
- chart/templates/secret-grafana-datasources.yaml
- chart/values.yaml
The README is updated to show the new config
options and restructured for readability. The new
image for the Timescale-Prometheus connector is used
along with TimescaleDB 1.7 on PG12.
> Use the alpha.2 image for the connector and update docs

- chart/templates/NOTES.txt
Updates notes to connect prometheus service port instead of pod port if the service type is ClusterIP
>  port-forwarding to the prometheus service

- chart/templates/prometheus-conf.yaml
Timescale-Prometheus helm chart v0.1.0-alpha.3 updated
the service name. This commit upgrades the config map
override.
Closes #28
> Update service name of pre-configured remote endpoints

- README.md
Patroni installation from Timescale Helm chart, which is used in this chart, creates an endpoint which can be leftover when uninstalling a Helm release. This can cause issues when deploying the chart with the same release name.
Closes #27
> Update README with instruction to remove leftover endpoint

- .github/workflows/generate.yml
- deploy/static/deploy.yaml
- generate-deploy-script.sh
Users which want to use static deployment resource to deploy to a
Kubernetes cluster can use the generated script instead of needing to
depend on Helm services.
> Add static deployment and generation script

- .github/workflows/generate.yml
- README.md
- chart/Chart.yaml
- chart/templates/prometheus-conf.yaml
- chart/values.yaml
- deploy/static/deploy.yaml
- generate-deploy-script.sh
Resolves #21 
Previously the configuration options for Timescale-Prometheus
were stored under the values for the connector. This created
confusion for users because the prometheus chart has a separate
remoteWrite configuration option. This refactor aims to make
it clear that the configuration for the timescale-prometheus
remote_write will go into the config map override
of prometheus.
> Refactor connector queue config values

- chart/templates/NOTES.txt
Update install notes to for usability. Add emojis, re-organize sections, simplify text. 
Some of this work may be less necessary because of the upcoming CLI, but perhaps good practice to clean this up.
Here is an example of how the install message looks now:
```
NAME: chart-1591739957
LAST DEPLOYED: Tue Jun  9 14:59:19 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
###############################################################################
👋🏽 Welcome to timescale-observability
✨ Auto-configured and deployed:
🔥 Prometheus
🐯 TimescaleDB
🤝 Timescale-Prometheus connector
📈 Grafana
###############################################################################
🔥 PROMETHEUS NOTES:
###############################################################################
TimescaleDB can be …
```
> Update install notes

- chart/templates/grafana-dashboards-conf.yaml
- chart/templates/grafana-datasources-sec.yaml
- chart/templates/grafana-db-sec.yaml
- chart/templates/grafana-db-user-conf.yaml
- chart/templates/grafana-db-user-job.yaml
- chart/values.yaml
- ts-obs/cmd/kubectl.go
- ts-obs/cmd/pgx.go
- Add port number to GF_DATABASE_HOST
- Read dbname and port number from values file
- OpenConnectionToDB now detects and supports external DB
> Make CLI compatible with Forge

- README.md
The docs failed to mention `--devel` in one instance, this got me
confused as the error given by helm in that case is not really helpful.
> Updated docs to add --devel to helm commands

- README.md
- chart/README.md
- cli/README.md
For reviewers: This reorganizes the readme so that the front-page readme is much shorter and to-the-point. It also emphasizes CLI usage. Details about the helm chart are moved into a secondary readme under chart/. Some other changes too.
> Change README to emphasize CLI tool.

- chart/values.yaml
Queries to the connector are much more effecient than
queries that go to prom server->remote_read to connector.
> Switch datasource from Prometheus server to connector

- README.md
- chart/Chart.yaml
- chart/README.md
- chart/values.yaml
The stable helm repository has been deprecated
and charts are now moved to their own repositories.
Also the versions for Prometheus and Grafana charts
are updated.
> Update refs to Prometheus and Grafana chart repos

- install-cli.sh
The <<< redirection is not available on dash (/bin/sh)
on linux systems, which makes our script and instructions
broken.
Fixes #66
> Make install-cli compatible with dash on Linux

- .github/workflows/generate.yml
- README.md
- cli/Makefile
- cli/README.md
- cli/e2e-tests.sh
- cli/tests/concurrent_test.go
- cli/tests/grafana_test.go
- cli/tests/installation_test.go
- cli/tests/main_test.go
- cli/tests/metrics_test.go
- cli/tests/portforward_test.go
- cli/tests/prometheus_test.go
- cli/tests/promlens_test.go
- cli/tests/testdata/f1.yml
- cli/tests/testdata/f2.yml
- cli/tests/testdata/f3.yml
- cli/tests/testdata/f4.yml
- cli/tests/timescale_test.go
1. Added e2e tests to CI
2. Changed the K8s tool from minikube to kind for e2e tests. As kind (k8s on Docker) is more light weight and easy run in local development machines. Added `e2e-tests.sh` script this creates kind cluster, runs e2e tests, & deletes kind cluster. Dropped minikube start, stop & delete logic from e2e tests.
3. Point the tobs in e2e tests to tobs in the bin directory as the latest tobs exe is placed in the bin directory after the build.
4. Comment memory requests in testdata files as `2Gi` requests lag underlying minikube/kind clusters while resource creation.
5. Comment tobs concurrent tests as this needs some re-work in running these tests.
6. Add badges to tobs README.md
Signed-off-by: Vineeth Pothulapati <vineethpothulapati@outlook.com>
> e2e tests evaluation in CI

- .github/workflows/generate.yml
- cli/cmd/portForward.go
- cli/cmd/promlens.go
- cli/cmd/promlensPortForward.go
- cli/cmd/promscale.go
- cli/cmd/promscalePortForward.go
- cli/tests/concurrent_test.go
- cli/tests/portforward_test.go
- cli/tests/promlens_test.go
- cli/tests/promscale_test.go
1. Separated promscale from promlens subcommand along with e2e tests.
2. Refactored code, flags from `connector` to `promscale`
Signed-off-by: Vineeth Pothulapati <vineethpothulapati@outlook.com>
> Add promscale subcommand

- cli/README.md
- cli/cmd/volume.go
- cli/cmd/volumeExpand.go
- cli/cmd/volumeGet.go
- cli/pkg/k8s/k8s.go
- cli/tests/volume_test.go
1.  Get Existing PVC's sizes
```
$ tobs volume get --prometheus-storage --timescaleDB-storage --timescaleDB-wal
PVC's of storage-volume
Existing size of PVC: storage-volume-tobs-timescaledb-0 is 150Gi
PVC's of wal-volume
Existing size of PVC: wal-volume-tobs-timescaledb-0 is 20Gi
PVC's of gg-prometheus-server
Existing size of PVC: tobs-prometheus-server is 8Gi
```
2. Expand Existing PVC's sizes
```
$ tobs volume expand --prometheus-storage 9Gi --timescaleDB-storage 151Gi --timescaleDB-wal 21Gi
PVC's of storage-volume
Successfully expanded PVC: storage-volume-tobs-timescaledb-0 to 151Gi
PVC's of wal-volume
Successfully expanded PVC: wal-volume-tobs-timescaledb-0 to 21Gi
PVC's of gg-prometheus-server
Successfully expanded PVC: tobs-prometheus-server to 9Gi
```
3. Expand command when trying …
> Add get, expand support for PVC's

- cli/README.md
maybe depending on how you reach the README.md, but the releases link is giving a 404 when using the link on "https://github.com/timescale/tobs" page, so replace it with full link
Second part of the diff is caused by doing a 'github' edit I guess, I don't see the diff on that line...
> README: releases link might give 404

- cli/cmd/helmShowValues.go
- cli/pkg/k8s/k8s.go
Don't use exec.Cmd.CombinedOutput() when execing as it makes redirection to yaml file prone to silent failures
> *NOTE:* this is not a fix for #96, just for the additional issue that the Helm Stderr pollutes the Stdout that is directed into the values.yaml
```
sven@x1carbon:~/src/github/timescaledb/tobs/cli$ tobs helm show-values | head
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
cli: false
timescaledb-single:
enabled: true
sven@x1carbon:~/src/github/timescaledb/tobs/cli$ ./bin/tobs helm show-values > /tmp/values.yaml| head
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
```
> exec helm Combined Stderr&Stdout problem for show-values

- chart/values.yaml
extraScrapeConfigs field in values.yaml actually expects a string - fixed that and also added a small example of using it
> Fixed extraScrapeConfigs: parameter example in values.yaml

- chart/templates/prometheus-conf.yaml
Hi.
I've also been unable to get alertmanager working with this helm chart. (see #99 )
By default, the alertmanger API endpoint discovery is disabled due to a target error in prometheus.yml during alertmanger communication.
I changed source_labels in prometheus.yml. So, It seems to be working well.
> Change alertmanager kubernetes_sd_config labels

- chart/templates/prometheus-conf.yaml
update Prometheus config according to the upstream Prometheus helm chart fix on alert-manager port config.
This PR addresses two things:
1. In tobs we follow the default Prometheus configuration from the Prometheus helm chart. There is alertManager port level update for alertManager service discovery. Here is the upstream merged [PR](https://github.com/prometheus-community/helm-charts/pull/353). In this PR we added the same fix to tobs Prometheus config. 
2. Viewing & editing the Prometheus config file in tobs was a bit messy previously as configmap YAML parsing was shrinking the Prometheus config into string due to trailing whitespaces, fixed it in this PR. Now users can interact with Prometheus config with much ease. 
Before:
```
prometheus.yml: "global:\n  evaluation_interval: 1m\n …
```
> Update Prometheus config

- cli/cmd/helm/delete_data.go
- cli/cmd/helm/helm_uninstall.go
1. Removed the duplicate code
2. Added additional secret deletion which isn't deleted on performing helm chart uninstall.
> fix tobs uninstall flow

- chart/templates/grafana-datasources-sec.yaml
- chart/values.yaml
- cli/cmd/install/install.go
- cli/cmd/uninstall/uninstall.go
- cli/cmd/upgrade/upgrade.go
- cli/cmd/version/version.go
- cli/pkg/helm/client.go
- cli/pkg/helm/client_impl.go
- cli/tests/ha-tests/ha_test.go
- cli/tests/helm-tests/helm_test.go
- cli/tests/upgrade-tests/upgrade_test.go
1. Add default Prometheus instance retention to `1d`. 
2. Change Promscale datasource name from Prometheus to Promscale. This will be used to display the name in Grafana UI. 
3. Tobs install should create secrets for versions >= `0.3.0`. Added the = which was missed. This is a bug only if a user installs the tobs by explicitly providing the version as `0.3.0`. **Note**: Installation based on version wasn't available in version 0.3.0. So this just makes the validation better. 
4. If the Kubernetes cluster is big with 10's of helm releases finding the existing tobs installation was failing as the helm client was timed out. So now to find the existing tobs helm release we will search in a specific namespace which makes finding the release much easier. 
5. For some reason if an upgrade is …
> Minor bug fixes

- cli/cmd/common/common.go
- cli/cmd/metrics/chunk_interval_get.go
- cli/cmd/metrics/chunk_interval_reset.go
- cli/cmd/metrics/chunk_interval_set.go
- cli/cmd/metrics/chunk_interval_set_default.go
- cli/cmd/metrics/metrics.go
- cli/cmd/metrics/retention_get.go
- cli/cmd/metrics/retention_reset.go
- cli/cmd/metrics/retention_set.go
- cli/cmd/metrics/retention_set_default.go
- cli/cmd/timescaledb/connect.go
- cli/cmd/timescaledb/port_forward.go
- cli/cmd/timescaledb/superuser/change_password.go
- cli/cmd/timescaledb/superuser/connect.go
- cli/cmd/timescaledb/superuser/get_password.go
- cli/cmd/timescaledb/superuser/superuser.go
- cli/cmd/upgrade/upgrade.go
- cli/main.go
- cli/pkg/pgconn/connection.go
- cli/pkg/timescaledb_secrets/create.go
- cli/tests/external-db-tests/main_test.go
- cli/tests/test-utils/common_utils.go
- cli/tests/tobs-cli-tests/metrics_test.go
- cli/tests/tobs-cli-tests/timescale_superuser_test.go
- cli/tests/tobs-cli-tests/timescale_test.go
Refactor `tobs timescaledb` command
Currently `tobs timescaledb` cmds i.e. `get-password`, `change-password`, `connect` use by default superuser creds. So to let users know that we are changing these cmds to 
```
tobs timescaledb superuser connect
tobs timescaledb superuser get-password
tobs timescaledb superuser change-password
```
However if the user wants to connect to DB with their own user creds they can use below cmd. In this option you can also configure `dbname`
```
tobs timescaledb connect <user> --dbname <db-name> 
```
**tobs timescaledb**
```
$ ./bin/tobs timescaledb          
Subcommand for TimescaleDB operations
Usage:
tobs timescaledb [command]
Available Commands:
connect      Connects to the TimescaleDB database
port-forward Port-forwards TimescaleDB server to localhost …
```
> Refactor tobs timescaledb & metrics cmds

- cli/go.mod
- cli/go.sum
- cli/pkg/k8s/client_impl.go
For bug report #169, running the `init()` function of `k8s.io/client-go/plugin/pkg/client/auth` in `./cli/pkg/client_impl.go` seems to fix the issue. 
According to the docs, I should test with the `cli/tests/e2e-tests.sh`, but current issues with posix sh
> Add blank import for k8s client auth in cli for gcp support

- cli/cmd/install/install.go
Currently, tobs install works if it is able to find `/tmp/.helmcache` and `/tmp/.hemrepo`. But if they aren't present the installation fails. As I'm trying to validate chart values without downloading the chart.
> Fix helm chart download sequence flow

- .github/CODEOWNERS
- .gitignore
- CODEOWNERS
Move CODEOWNERS to .github dir since it only applies to GitHub and we want the root clean.
> Move CODEOWNERS to .github

- cli/pkg/pgconn/connection.go
- cli/pkg/pgconn/connection_test.go
Database passwords frequently contain characters that must
be URL encoded when put in the Postgres connection URI. If
not, the URI is invalid and will not work. This addresses
bug report in #199.
> URL encode database connection URI components

- cli/cmd/install/install.go
- cli/cmd/uninstall/uninstall.go
- cli/cmd/upgrade/upgrade.go
- cli/go.mod
- cli/go.sum
- cli/pkg/k8s/client.go
- cli/pkg/k8s/client_impl.go
- cli/pkg/otel/otel-utilities.go
This PR includes
1. Restructure Promscale values for connection details and update the connection details by assigning the `db-passowrd`/`db-uri` to respective value fields so the Promscale helm-chart will perform the DB secret creation. 
2. Delete `jaegerPromscaleQuery` section in `opentelemetryOperator`
3. Delete `otel-collector` CR created by us in the previous version and capture CR from `values.yaml` and re-create it with small changes. 
4. Upgrade `Kube-Prometheus` CRDs.
5. Upgrade `OpenTelemetry-Operator` CRDs.
6. Upgrade `Cert-Manager` if installed by us, by taking the confirmation message from the user. If no other CRs managed by cert-manager is created by the user other than the CRs created by tobs. If found other CRs outside the scope of tobs managed by cert-manager created by …
> Upgrade path for 0.8.0

- chart/values.yaml
This is required to get metrics flow running.
cc @VineethReddy02
> chart: add metrics pipeline

- chart/README.md
- chart/docs/upgrades.md
tobs-credentails -> tobs-credentials
> fix typo in README

- .goreleaser.yaml
- cli/.goreleaser.yml
Follow-up to #228 as it turned out we have goreleaser config in `cli/` directory.
> *: fix location of goreleaser config

- chart/values.yaml
Fixing type-casting issues
Requires https://github.com/timescale/promscale/pull/1159
> chart: use proper types for enabling parts of the stack

- chart/values.yaml
By default we should use chart default image. This allows us to set image in one place (timescaledb-single helm chart).
> chart: drop explicit tag for timescaledb

- .github/renovate.json
This PR adds automatic management of following dependencies:
- helm charts
- golang packages
- github actions
golang packages updates are grouped together and should result in one PR with all updates. The same applies to helm charts. Github actions are not grouped as their update frequency is much lower and it might be better to evaluate each update separatelly.
> .github: add automatic dependency management via renovate

- .github/env
- .github/renovate.json
- .github/workflows/cli.yml
- .github/workflows/go-releaser.yml
- .github/workflows/tests-schedule.yml
This is an extension on what renovate can do.
Few months ago we moved to handing golang and golangci-lint versions across all github action workflow files to a single `.github/env` file. This file was read in each workflow job and simplified managing dependencies.
However, since renovate can update dependencies automatically and allows to do this based on regexes, we can simplify our github action workflow files while still making tools up to date. I've tested a similar functionality with https://github.com/thaum-xyz/ankhmorpork/blob/master/.github/renovate.json and it resulted in [a correct PR](https://github.com/thaum-xyz/ankhmorpork/pull/116)
Small additional change - I found how to set `labels` once and extend it with `addLabels` config. This simplifies managing labels as …
> .github: allow renovate to handle github action envs

- .github/renovate.json
This wasn't clear when reading documentation, but it became clearer by looking at renovate codebase at https://github.com/renovatebot/renovate/blob/main/lib/datasource/golang-version/index.ts
Fixes #269
> .github: set correct depName for renovate regexManager

- .github/renovate.json
- .github/workflows/cli.yml
- .github/workflows/go-releaser.yml
- .github/workflows/helm-releaser.yml
- .github/workflows/tests-schedule.yml
Finalizing what was started in https://github.com/timescale/tobs/pull/268
Logic behind this PR was tested in my fork and resulted in a correct PR as seen in https://github.com/paulfantom/tobs/pull/10
`k8s.io/client-go` is excluded from automatic updates as the project switched to using different version notation which confuses renovatebot.
> .github: finetune regex updates via renovate

- cli/cmd/upgrade/upgrade.go
As in title
Label `app` was deprecated and can cause issues with upgrades. Fortunately, we have enough confidence when using 2 remaining labels that PVCs were installed by tobs and thus we can remove `app` from being used.
> Remove unnecessary label selector in upgrade path

- chart/Chart.yaml
- chart/values.yaml
timescaledb helm chart 0.11.0 changed the way it provisions secrets and thus change like this is needed.
This is a quickfix as proper fix would be to switch from provisioning Secret by tobs and use helm to do this. This method is worked on in https://github.com/timescale/tobs/pull/280
> Bumping timescaledb helm chart to 0.11.0 and adding necessary changes

- chart/Chart.yaml
- cli/cmd/version/version.go
- install-cli.sh
Bumping dependencies to prepare for 0.9.0 release.
This is blocked by #228
> Release 0.9.0

- chart/README.md
The flag `-n <name>` is not needed in the docs
> Docs: Remove typo

- chart/values.yaml
As in title
This is building on work done in https://github.com/timescale/promscale/pull/885
Additionally, this will also include promscale alerts when https://github.com/timescale/promscale/pull/1271 is merged, but promscale PR is not blocking this one.
Resolves https://github.com/timescale/o11y-team-applications/issues/186
> chart: use promscale serviceMonitor instead of annotation-based scraping

- .github/renovate.json
- .github/workflows/cli.yml
- chart/README.md
- chart/templates/otel-auto-instrumentation.yaml
- chart/templates/otel-collector.yaml
- chart/values.yaml
- cli/cmd/install/install.go
- cli/pkg/k8s/client_impl.go
- cli/tests/helm-tests/helm_test.go
- cli/tests/installation-tests/installation_test.go
- cli/tests/test-utils/common_utils.go
- cli/tests/testdata/e2e-values.yaml
- cli/tests/tobs-cli-tests/concurrent_test.go
Few things are done in this PR:
- `--tracing` flag is deprecated, but still present
- tracing is enabled by default (fixes https://github.com/timescale/o11y-team-applications/issues/161)
- otel collector CR is deployed with helm instead of artisan deployment in tobs CLI
This PR is based on top of https://github.com/timescale/tobs/pull/305 and as such it is created as a draft.
> *: deploy otel by default and move deployment of otel collector resource to helm

- chart/values.yaml
Right now promscale does not support compression, so tobs should disable compression by default.
Spawned from https://github.com/timescale/promscale/issues/1292
> chart: disable otel compression

- chart/dashboards/apm-home.json
- chart/dashboards/apm-service-dependencies-upstream.json
Transfer the updated APM dashboard experience from the promscale repo. There were changes in the traces enums, and apparently some updates in the apm home overview.
```release-note
APM Experience dashboards updated to latest version.
```
> Transfer dashboards from promscale to tobs, updating enums

- chart/Chart.yaml
- chart/values.yaml
- Bumping promscale to use alpha version for testing
```release-note
Switching to promscale 0.11.0 which requires timescaleDB
```
> chart: bump promscale chart version and pin timescaledb image to dev one

- chart/values.yaml
We included dashboards in few places, but they were still not showing up in grafana. This PR should change it and allow grafana sidecar to pick up APM dashboards.
```release-note
Fix inclusion of APM dashboards
```
> chart: fix inclusion of promscale dashboards in tobs

- cli/cmd/install/install.go
- Make it clearer that `--tracing` will be deprecated.
- Change deprecation date to post 0.10.0 release (we wanted to deprecate in release after the one we do tomorrow, not in 2 releases time).
```release-note
```
> cli: tracing flag deprecation notice

- .github/PULL_REQUEST_TEMPLATE.md
- cli/.goreleaser.yml
- changing goreleaser config to use github changelog format
- changing goreleaser config to allow closing milestones
- Fixing PR template to allow better usage of goreleaser changelog format
> chore: adjust goreleaser to use more meaningful changelog format

- cli/cmd/install/install.go
Fixing #358
Removing deprecated flags.
> cli/cmd/install: remove deprecated flags and hard exit on their usage

- chart/templates/NOTES.txt
> chart: remove mentions of tobs CLI from helm notes

- .github/workflows/project-management.yml
> .github: create milestones only for minor releases, not for patches

- chart/values.yaml
Signed-off-by: Prem Saraswat <prmsrswt@gmail.com>
Fixes #351 
This PR configures Prometheus to run 2 replicas with required external labels. It also enables the HA mode in Promscale, so that it doesn't ingest duplicate data.
> Deploy Prometheus in high availability mode

- chart/values.yaml
- cli/tests/tobs-cli-tests/main_test.go
To ensure high-availability of the monitoring stack we should deploy prometheus as well as alertmanager in HA modes. Prometheus HA deployment was accomplished in https://github.com/timescale/tobs/pull/416. This PR is a continuation and ensures alertmanager is also running in HA.
This is also aligning tobs with prometheus-operator project recommendations regarding deployment topology.
> chart: deploy alertmanager in HA mode

- chart/Chart.yaml
- cli/cmd/version/version.go
- install-cli.sh
> Prepare 0.11.0 release

- chart/Chart.yaml
- cli/cmd/version/version.go
- install-cli.sh
Removing hard dependency on kubernetes 1.23 as this version is not widely available in multiple clouds. We will reconsider enabling this option in future releases.
Fixing https://github.com/timescale/tobs/issues/440
> Remove kube version constraint

- .github/workflows/cli.yml
- Makefile
- chart/Chart.yaml
- chart/templates/grafana-datasource-job.yaml
- chart/templates/grafana-datasource-sql.yaml
- chart/templates/timescaledb-toolkit.yaml
- cli/cmd/version/version.go
- install-cli.sh
- scripts/check-datasources.sh
Two bugfixes at a price of one:
- Fixing setting SQL datasource by reverting deletion of Job object
- Fixing usage of timescaledb_toolkit as it is still not enabled by default on all dbs.
Since those issues are recurring, I added a rudimentary shell script to check if grafana can query for `timescaledb_toolkit` extension. This check is in shell script as we are approaching refactoring of our test suite and I didn't want to add more complexity to the migration path.
> Fix sql datasource

- .github/workflows/cli.yml
- chart/values.yaml
Setting default resource requirements and limits. Closes #154
Adding resource requests to:
- timescaleDB
- promscale
- prometheus (incl. config-reloader)
- alertmanager (incl. config-reloader)
- prometheus-operator
- grafana
- kube-state-metrics
- node_exporter
- otel-operator 
Adding resource limits to:
- alertmanager (incl. config-reloader)
- prometheus-operator
- grafana
- kube-state-metrics
- node_exporter
- otel-operator 
All resource information are largely based on settings from kube-prometheus project (jsonnet one). Resource requirements were lowered to match values noted by running tobs in `kind` cluster as well as values from clusters with longer run time.
Requirements listed in this PR sum up to:
```
mem: 4GB + (# nodes * 50Mi)
cpu: 0.5core + (# nodes * 30milicore)
```
We will …
> Set default resource requests and limits to tobs deployment

- .github/workflows/project-management.yml
Adding stale bot to handle issues and PRs labeled with either `question` or `needs-more-info`.
The bot will mark issues as stale (noted by `stale` label) after 30 days of no activity and close them after another 30 days.
> .github: add stale bot

- Makefile
Sometimes when running `make helm-install` will error due to cert-manager not being up in time.  Add a timeout of `120s` to ensure there is enough time for it to start before proceeding.
> Add timeout to kubectl wait command

- chart/dashboards/apm-home.json
- chart/dashboards/apm-service-overview.json
Update APM dashboards trace reference URLs.
As the default version of Grafana in tobs is `9.0.2` this requires trace reference URLs to be updated. 
> Update trace reference URLs in APM dashboards

- chart/Chart.yaml
- chart/docs/upgrades.md
- chart/templates/NOTES.txt
- chart/templates/grafana-datasources-sec.yaml
- chart/templates/otel-auto-instrumentation.yaml
- chart/templates/otel-collector-service-monitor.yaml
- chart/templates/otel-collector.yaml
- chart/templates/otel-operator-service-monitor.yaml
- chart/values.yaml
Added the following images versions
- opentelemetry-opertaor
- kube-state-metrics
- node-exporter
- alertmanager
- prometheus-operator
- prometheus
Changed `opentelemetryOperator` to `opentelemetry-operator` in `values.yaml` so we can support passing values into the opentelemetry-operator Helm chart.
Updated opentelemetry-operator Helm chart from `0.9.2` -> `0.9.3`
> Lock versions of chart dependencies that were missing

- chart/values.yaml
With the upgrade to Promscale 0.13.0 Helm chart it seems we are no longer compatible with the timescaledb-ha image we ship with timescaledb-single Helm chart.  This PR updates the version from `pg14.3-ts2.7.0-p0` -> `pg14.4-ts2.7.2-p0`
> Update timescaledb-ha image to work with promscale extension

- .github/renovate.json
By separating helm chart updates from helm values updates we can still have automatic updates for container images regardless of changes carried by the helm charts.
By example instead of getting one PR like https://github.com/timescale/tobs/pull/515 which updates container images and otel-operator helm chart, we should get 2 PRs - one for image updates and one for otel-operator helm chart. This in turn allows us to still update images regardless of issues with otel-operator helm chart.
> .github: separate updating helm values from helm charts

- chart/templates/timescaledb-grafana-datasource.yaml
There would have been an issue during the Helm upgrade process where the `lookup` function inside the template would have looked at the incorrect secret.  This was set to look at `custom-init-scripts` but it should be `custom-secret-scripts`.
> Correct secret name for lookup() function

- .github/renovate.json
1) Fixing cert-manager updates via renovate
2) Allowing renovate to bump chart version when doing dependency chart updates
3) Groupping helm values updates with helm dependencies updates to allow chart version updates. This is needed as https://github.com/renovatebot/renovate/issues/8231 is not complete.
4) Testing our CI gating of version updates.
- fixes #
> .github: reconfigure renovate

- chart/Chart.yaml
- chart/templates/connection-secret-job.yaml
- chart/values.yaml
Embedding mechanism for propagating database password in promscale helm chart may have been a mistake as it casues issues like https://github.com/timescale/promscale/issues/1474. To keep similar logic we can move it into tobs and use `connectionSecretName`.
It allows us to fix https://github.com/timescale/promscale/issues/1474. Also it paves a path to fix what was reported in https://iobeam.slack.com/archives/C03L8NYLUF7/p1660571016688299
> chart: use connectionSecretName to set promscale connection to db

- chart/Chart.yaml
- chart/templates/connection-secret-job.yaml
Access to service account token should be restricted 
- fixes #461, https://github.com/timescale/promscale/pull/1559
> restrict service account token from being accessed

- .github/workflows/tests.yml
- Makefile
Updating Kubernetes and cert-manager versions in Makefile.  Adding in `helm-upgrade` target and removing dependency  from `cert-manager` to allow for `helm-upgrade` to function.
> Switch up Makefile targets, update kind versions

- .github/renovate.json
Judging by https://github.com/timescale/tobs/pull/551 our renovate configuration is not correct. According to https://docs.renovatebot.com/configuration-options/#bumpversion value of `true` is not allowed and we need to choose which semver component to bump automatically. This PR should fix the issue and we can use https://github.com/timescale/tobs/pull/551 as a testbed.
- fixes #
> .github: make renovate always bump helm chart minor version

- .github/workflows/tests.yml
- Makefile
- chart/Chart.yaml
- chart/README.md
- chart/ci/externaldb-values.yaml
- chart/templates/timescaledb-grafana-datasource.yaml
- docs/tobs-external-db.md
Create a way to connect to and setup Grafana to query an external TimescaleDB if it's not provisioned by tobs.
You can now easily install tobs to connect to an external (to tobs) TimescaleDB.  This can be achieved by setting `timescaledb-single.enabled=false`, setting the password for the TimescaleDB `postgres` role in `promscale.connection.password`, and the host URI for timescale in `promscale.connection.host`.
This at minimum will setup Promscale and the Grafana datasource connections correctly to the external TimescaleDB.
> Setup connection to external TimescaleDB

- chart/Chart.yaml
- chart/values.yaml
- docs/upgrades.md
Update Promscale Helm chart to the latest version `13.0.0` and update relevant documentation
- fixes #509
> Bump promscale helm chart to 13.0.0

- docs/upgrades.md
Add some update documentation when updating tobs from `v0.11.x` to `v12.x.x`
- fixes #553
> Updating documenation around issues updating from v0.11 to v12

- chart/Chart.yaml
- chart/README.md
We needed better documentation surrounding the chart installation and uninstallation process.
* Add docs to make sure we recommend installing tobs to its own namespace
* Add better uninstallation documentation and make sure everything is uninstalled
* Updated Markdown formatting a bit...
- fixes: #365 
- fixes: #562
> Update chart documentation

- Makefile
- chart/Chart.yaml
- chart/values.yaml
This PR is mainly bumping promscale to 0.14.0. Additionally it is using latest timescale helm chart and unlocking timescaledb image version used in tests (this way we only need to bump image in the upstream helm chart).
- fixes #
> chart: bump promscale version to 0.14

- chart/Chart.yaml
- chart/values.yaml
This should allow retreiving data from prometheus even when promscale is down and thus increasing overal reliability of the stack.
Recent outage surfaced that when promscale is down, our whole monitoring system can go down due to misconfigured remote_read. Before change from this PR prometheus ALWAYS wanted to get data from promscale when querying data or computing recording rules. This in turn created a single point of failure even in a setup with prometheus in HA. This PR is fixing this major issue and allows prometheus to be used as a buffer when promscale is down.
- fixes #
> do not force prometheus into reading recent data from promscale

- chart/Chart.yaml
- chart/templates/NOTES.txt
- chart/templates/_helpers.tpl
With the merge of #546 the notes/instructions that are printed once tobs is installed render incorrectly.
- fixes #573
> Fix printing of instructions after tobs is installed

- .github/workflows/tests.yml
- chart/Chart.yaml
- chart/values.yaml
- docs/upgrades.md
Bump chart version to `15.0.0`
This PR supersedes #594 
| Package | Update | Change |
|---|---|---|
| grafana/grafana | patch | `9.1.6` -> `9.1.7` |
| [kube-prometheus-stack](https://togithub.com/prometheus-operator/kube-prometheus) ([source](https://togithub.com/prometheus-community/helm-charts)) | minor | `40.1.0` -> `40.3.1` |
| [opentelemetry-operator](https://opentelemetry.io/) ([source](https://togithub.com/open-telemetry/opentelemetry-helm-charts)) | minor | `0.12.2` -> `0.13.0` |
| quay.io/prometheus/node-exporter | minor | `v1.3.1` -> `v1.4.0` |
| [timescaledb-single](https://togithub.com/timescale/helm-charts) | minor | `0.16.3` -> `0.17.0` |
| [helm/chart-testintg-action](https://github.com/helm/chart-testing-action) | minor | `2.3.0` -> `2.3.1` |
Updated the …
> Updating Dependencies, bump chart to 15.0.0

- chart/Chart.yaml
* Update [timescaledb-single](https://github.com/timescale/helm-charts/tree/main/charts/timescaledb-single) Helm chart to `0.18.0`
> Bump timescaledb-single helm chart to 0.18.0

- chart/Chart.yaml
- chart/values.yaml
Just applying what is recommended in https://docs.timescale.com/promscale/latest/recommendations/config-recomm/#database-configuration
I decided to not disable `synchronous_commit` as it can lead to unexpected issues for some. However I left it there as a comment for discoverability.
- fixes #
> chart: tune TSDB for promscale usage

- chart/Chart.yaml
- chart/dashboards/promscale.json
This is adding a way to select datasource and namespace in promscale dashboard.
I am going to port that also upstream (to promscale repo), so our copier script will work just fine.
- fixes #
> Improve promscale dashboard

- chart/Chart.yaml
- chart/dashboards/promscale.json
- scripts/sync-mixins.sh
Propagation of fixes from https://github.com/timescale/promscale/pull/1734
This is also removing dead code from mixin synchronizer script as DS_PROMETHEUS variable is no longer present in promscale dashboard.
- fixes #
> chart: propagate promscale dashboard fixes

- chart/Chart.yaml
We merged #624 and #617 when both PRs were supposed to release tobs version 17.8.0. This resulted in #617 not being a part of any release now. This PR is fixing this by bumping chart version to create a release.
- fixes #
> release 17.9.0 with new dashboard from PR619

- chart/Chart.yaml
- chart/dashboards/postgres-details.json
In some cases it is possible that data density doesn't align with grafana `$__rate_interval` and resulting panels are empty. This PR is adding a minimum interval for all panels so data should always be presented.
Additionally this is fixing and optimizing dashboard variables to use less expensive queries.
- fixes #
> chart: add min interval for rate() queries

- chart/Chart.yaml
- chart/dashboards/postgres-details.json
I noticed that in https://github.com/timescale/tobs/pull/626 I missed adding min interval to one of the panels. This PR is fixing that mistake plus it is putting data coming from bgwriter into a single row to make dashboard more compact.
- fixes #
> chart: re-arrange bgwriter panels in postgres details dashboard

- chart/Chart.yaml
- chart/values.yaml
Moves the stats temporary file outside the data directory to improve
disk performance.
According to the docs:
```
stats_temp_directory (string)
Sets the directory to store temporary statistics data in. This can be
a path relative to the data directory or an absolute path. The default
is pg_stat_tmp. Pointing this at a RAM-based file system will decrease
physical I/O requirements and can lead to improved performance. This
parameter can only be set in the postgresql.conf file or on the server
command line.
```
PG15 rewrote the statistics collector, from that version onward the
statistics are no longer stored in files and the `stats_temp_directory`
config options was deprecated. Once the DB upgrades to PG15 this setting
can be removed.
> Set stats_temp_directory to tmp directory

- chart/Chart.yaml
- chart/values.yaml
- docs/upgrades.md
Updating `kube-prometheus-stack` to the latest version `v42.2.0`.  Which is meant to fix issues with PR's #657 & #665 
- fixes #665 
- fixes #657
> upgrade kube-prometheus-stack to latest version
