- README.md
- chart/Chart.yaml
> Adjust timescale-prometheus version

- README.md
- chart/values.yaml
Also the Prometheus Push Gateway is disabled by default.
> Update the README with info on configurable properties

- chart/templates/NOTES.txt
These are notes displayed to the user after performing a helm install.
> Add post install notes

- LICENSE
- NOTICE
- README.md
Add License and Notice. Also add a blurb about contributing to README.
> Add legalese

- chart/templates/NOTES.txt
Some of the command had the wrong variable interpolation.
> Fix templating logic in NOTES.txt

- chart/templates/NOTES.txt
> GRAFANAPOD line typo fix

- chart/values.yaml
> Increase default WAL and data disk size

- install-cli.sh
Put everything inside a function so that nothing actually done until full content is
downloaded.
See https://www.arp242.net/curl-to-sh.html
> Prevent potential problems with partial content/download

- install-cli.sh
Instruct people to copy binary into /usr/local/bin
so that the binary is easily accessed after restart
> Change instructions on how to install tobs

- README.md
- chart/Chart.yaml
- chart/README.md
- chart/templates/NOTES.txt
- chart/values.yaml
- cli/cmd/kubectl.go
- cli/cmd/pgx.go
- cli/cmd/promlensPortForward.go
- cli/tests/installation_test.go
- cli/tests/testdata/f1.yml
- cli/tests/testdata/f2.yml
- cli/tests/testdata/f3.yml
- cli/tests/testdata/f4.yml
- deploy/static/deploy.yaml
- install-cli.sh
The project timescale-prometheus was renamed to Promscale.
Adjust the name here and also bump version to beta.5
> Change to point to Promscale

- cli/cmd/kubectl.go
- cli/go.sum
Signed-off-by: tuapuikia <dknyvice@gmail.com>
Patch to resolve https://github.com/timescale/tobs/issues/68
> Add auth support for kubectl cmd

- cli/README.md
- cli/cmd/volumeExpand.go
- cli/pkg/k8s/k8s.go
- cli/tests/volume_test.go
Signed-off-by: Vineeth Pothulapati <vineethpothulapati@outlook.com>
> Add flag to restart pods on pvc expansion

- chart/templates/NOTES.txt
- cli/cmd/helm/upgrade.go
- cli/cmd/helm/version.go
- cli/pkg/k8s/k8s.go
- cli/tests/test-utils/k8s-utilities.go
- cli/tests/testdata/chart1/templates/_helpers.tpl
- cli/tests/testdata/chart2/templates/_helpers.tpl
- cli/tests/testdata/chart2/values.yaml
- cli/tests/testdata/f1.yaml
- cli/tests/testdata/f2.yaml
- cli/tests/testdata/f3.yaml
- cli/tests/testdata/f4.yaml
- cli/tests/tobs-cli-tests/installation_test.go
- cli/tests/tobs-cli-tests/portforward_test.go
- cli/tests/upgrade-tests/upgrade_test.go
This PR needs to be merged after #126
> Fix scheduled tests

- chart/values.yaml
- cli/tests/testdata/main-values.yaml
add additional scrape config to scrape all pods and services in the k8s cluster
> Add additional scrape config

- cli/pkg/utils/utils.go
change `combinedOut` to `output` as using combinedOut includes warnings if there are any and fails to parse operations of expected results...
This is observed commonly helm lags out warnings...
> If noticed any warnings log them and parse the output

- cli/cmd/uninstall/uninstall.go
Currently, when we perform uninstall but not deleting the actual data, we are deleting the TimescaleDB secrets. When we re-deploy tobs to use the older PVC's the auth with PVC's fail as we deleted the creds during the previous uninstall that are needed to access the data in PVCs. 
The fix here only deletes secrets on delete data operation.
> Fix uninstall persist secrets when not deleting data

- chart/Chart.yaml
> chart: bump promscale helm chart to 0.8.0

- .github/workflows/helm-releaser.yml
Put releases in the timescale repo automatically.
> Add automatic helm chart publishing to release process

- .github/workflows/tests-schedule.yml
- chart/Chart.yaml
- chart/values.yaml
- cli/cmd/version/version.go
- deploy/static/deploy.yaml
- install-cli.sh
Note: Before releasing we need to fix Promscale helm chart issue
```
Downloading promscale from repo https://charts.timescale.com
Error: could not download s3://charts.timescale.com/promscale-0.8.0.tgz: scheme "s3" not supported
Save error occurred:  could not download s3://charts.timescale.com/promscale-0.8.0.tgz: scheme "s3" not supported
```
> Release 0.8.0

- .github/workflows/helm-releaser.yml
> fix incorrect helm releaser CI job

- chart/values.yaml
> chart: ingest metrics from OTel collector

- .goreleaser.yaml
As in title.
This would allow us to change release notes before them being public.
> *: add create release draft with goreleaser

- chart/Chart.yaml
- cli/cmd/upgrade/upgrade.go
> chart: update chart dependencies

- chart/Chart.yaml
> chart: bump timescaledb-single to latest release

- .github/workflows/helm.yml
- chart/templates/NOTES.txt
Fixing issues with incorrect templating for NOTICE.txt file and trying to prevent future such issues by adding a rudimentary testing in CI.
> chart: fix templating in notice file

- .github/CODEOWNERS
> .github: switch code ownership to a subteam

- install-cli.sh
> Shell typo: use `=`

- cli/cmd/install/install.go
As in title.
Also addressed https://github.com/timescale/tobs/pull/305#discussion_r860618723 in this PR.
This PR is building on top of https://github.com/timescale/tobs/pull/305 and until that PR is merged this one is in draft.
> cli/cmd: deprecate usage of flags related to timescaleDB secrets

- chart/templates/NOTES.txt
Fixes #262 
Fixes #284
```release-note
Fixing installation notes to not refer to outdated tobs subcommands
```
> chart: fix installation notes

- chart/values.yaml
- cli/tests/testdata/e2e-values.yaml
As in the title
```release-note
Fix incorrect jaeger datasource url
```
> *: point grafana to correct promscale address for traces retreival

- chart/templates/timescaledb-toolkit.yaml
As in title
```release-note
Enabled toolkit extension on timescaleDB
```
> chart: enable timescaledb-toolkit extension

- chart/values.yaml
Minor bump of promscale development image
```release-note
```
> chart: bump promscale image

- chart/Chart.yaml
- cli/cmd/version/version.go
Releasing RC.1.
```release-note
```
> *: create 0.10.0-alpha release

- chart/values.yaml
Quick fix to address issues discovered in https://github.com/timescale/promscale/issues/1344
```release-note
Prevent double scraping of promscale metrics
```
> chart: disable annotation-based scraping for promscale

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/support.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/cli.yml
- .mdox.validate.yaml
- Makefile
- README.md
- chart/README.md
- chart/docs/upgrades.md
- chart/docs/values-config.md
- cli/README.md
As in title
Docs formater and link checker is the same as in https://github.com/timescale/promscale/pull/1340
> chart: add upgrade instructions and format docs

- .github/workflows/project-management.yml
GitHub actions will now:
- assign newly opened issues to a project
- close milestone on release
- create new milestones
cc @VineethReddy02 @ramonguiu 
*Please put a one-line changelog entry below. This will be copied to the changelog file during the release process.*
```release-note
```
> .github: use GH action for project management

- .gitignore
- chart/templates/otel-auto-instrumentation.yaml
- chart/templates/otel-collector.yaml
- hard code init container images
- remove extra tobs prefix from collector
- change port and hostname for Instrumentation to find Collector
Tested and works well, LGTM
> Fix Otel Operator auto-instrumentation

- chart/values.yaml
*Please put a one-line changelog entry below. This will be copied to the changelog file during the release process.*
```release-note
Fixing issues with APM dashboards by bumping default grafana version
```
> chart: bump grafana image version

- .gitignore
- chart/templates/otel-auto-instrumentation.yaml
- chart/templates/otel-collector.yaml
- chart/values.yaml
Backporting bugfixes to a release branch
*Please put a one-line changelog entry below. This will be copied to the changelog file during the release process.*
```release-note
```
> [release-0.10] Backport bugfixes

- chart/values.yaml
Closes #379
Just fixing some broken configuration, see related issue
-  `BUGFIX` (non-breaking change which fixes an issue)
Fix metric ingestion in opentelemetry-collector.
> Fix prometheusremotewrite endpoint

- chart/templates/NOTES.txt
Remove Jaeger from the list of components installed printed when tobs install succeeds
*Please put a one-line changelog entry below. This will be copied to the changelog file during the release process.*
```release-note
Remove Jaeger from the list of components printed at the end of a successful tobs installation
```
> Remove Jaeger from the message tobs prints after tobs install

- cli/cmd/install/install.go
- cli/cmd/upgrade/upgrade.go
Export ConfirmActions to fix #382
> Export InstallSpec.ConfirmActions to fix #382

- chart/templates/NOTES.txt
- Changing commands to ones that work
- Fixing formatting
- Removing notes about PromLens as we are going to remove it soon
- Separated Alertmanager into its own section
- increased line character limit to 120
Fixes #387
> chart/templates: fix instructions shown in helm notes

- chart/values.yaml
Slowly deprecating promlens deployment.
Related to #369
> chart: disable promlens by default

- .github/workflows/cli.yml
- README.md
- cli/Makefile
- cli/tests/kind-1.21.yaml
- cli/tests/kind-1.22.yaml
- cli/tests/kind-1.23.yaml
- cli/tests/kind-1.24.yaml
Bumping supported kubernetes version. Lowest possible is 1.23 due to issues detected in https://github.com/prometheus-operator/kube-prometheus/pull/1768
Related to #364
> *: bump supported kubernetes versions

- .github/workflows/helm.yml
- chart/Chart.yaml
Finalizing kubernetes compatibility lock.
Closes #364 
> Specify minimum kubernetes version

- cli/tests/testdata/e2e-values.yaml
Disabling telemetry in CI tests.
Fixes #349
Relates also to https://github.com/timescale/tobs/issues/360 as configuration added here shouldn't be in default values.yaml file, but it is necessary for test purposes.
> cli/tests/testdata: disable telemetry in tests

- chart/templates/otel-collector-service-monitor.yaml
- chart/templates/otel-operator-service-monitor.yaml
Adding ServiceMonitors for otel-operator and otel-collector to allow gathering metrics from those components.
Fixes #366
> chart: add ServiceMonitors to gather metrics from otel components

- RELEASE.md
As in title.
Fixes https://github.com/timescale/tobs/issues/361
> *: include release instructions

- .github/workflows/project-management.yml
> .github: assign issues to o11y-services board

- .github/CODEOWNERS
> .github: change code ownership

- chart/Chart.yaml
- chart/values.yaml
- cli/cmd/version/version.go
- install-cli.sh
Main change is to bump promscale to 0.12.0
> Release 0.11.1

- chart/Chart.yaml
- chart/values.yaml
- cli/cmd/version/version.go
- install-cli.sh
> sync release branch with master

- chart/dashboards/promscale.json
> chart: propagate dashboards from promscale repo

- .github/workflows/cli.yml
- Makefile
- chart/Chart.yaml
- chart/templates/grafana-datasource-job.yaml
- chart/templates/grafana-datasource-sql.yaml
- chart/templates/timescaledb-toolkit.yaml
- chart/values.yaml
- cli/cmd/version/version.go
- install-cli.sh
- scripts/check-datasources.sh
> Sync Release 0.11 into master branch

- .github/renovate.json
- .github/workflows/sec-audit.yml
- .gitignore
- Makefile
- kubescape-exceptions.json
This is adding an automated security scanner in for of `kubescape`. It is basically a propagation of similar work done in [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) project.
While adding this scanner I found few issues which we might want to tackle later. Some of them were already tackled in [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) project but never ported to [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) and as such did not land in tobs:
- https://github.com/timescale/tobs/issues/457
- https://github.com/timescale/tobs/issues/458
- https://github.com/timescale/tobs/issues/459
- https://github.com/timescale/tobs/issues/460
- …
> Automated Security Scanner

- chart/Chart.yaml
> Update timescaledb-single helm chart version

- chart/Chart.yaml
- chart/values.yaml
Requires https://github.com/timescale/promscale/pull/1495
Requires promscale 0.13.0 to be released.
> Bump promscale and remove stale settings.

- RELEASE.md
Update `RELEASE.md` documentation to reflect the branching change from `master` to `main`
> Update to correct branch name for release docs

- scripts/sync-dashboards.sh
> scripts: make dashboard sync script compatible with BSD version of sed

- Makefile
- chart/Chart.yaml
- ct.yaml
Minor cleanup to ct configuration and also a small test to our automated release process.
Explanation behind each change is done in inline comments.
- fixes #
> chore(tooling): cleanup chart-testing configuration and validate maintainers in CI

- .github/renovate.json
Fix renovate config
- fixes #269
> Change true to be a string

- chart/Chart.yaml
- chart/ci/default-values.yaml
- chart/ci/externaldb-values.yaml
- chart/templates/tests/test-up-timescaledb.yaml
Helm test to check if components of the stack are actually up and running
- fixes # https://github.com/timescale/tobs/issues/324
> Add tests to check up status for all components

- chart/Chart.yaml
- chart/values.yaml
As in title. We'll need to update timescale image before merging this.
cc @jgpruitt 
- fixes #
> Tune timescaledb with promscale profile

- chart/Chart.yaml
- chart/values.yaml
Updates Promscale Helm chart to latest version `14.1.2` and updates links to documentation for promscale and timescaledb-single Helm charts.
> Update promscale helm chart to latest version

- .github/workflows/tests.yml
- Makefile
- scripts/sync-mixins.sh
Adding checking of shell scripts. Since our development scripts from `scripts/` are less important that ones from `chart/scripts/` I decided to use different severities when linting those scripts, hence running shellcheck twice.
This PR is building on top of https://github.com/timescale/tobs/pull/574 and will need rebase after menitioned PR is merged.
- fixes #
> chart: improve make targets and add cleanup target

- chart/Chart.yaml
- chart/values.yaml
Remove outdated comment
- fixes #592
> Remove outdated comments

- chart/Chart.yaml
- chart/dashboards/promscale.json
Updating promscale helm chart (which contains promscale alerts) and regenerating promscale dashboard.
- fixes #
> update promscale mixin

- .github/renovate.json
This collides with our precesses related to issues management and causes unnnecessary notifications.
Previous setting collides with our processes related to issues management and causes unnecessary notifications.
PR doesn't require version bump as it doesn't touch chart code.
- fixes #
> .github: do not close dependency dashboard issue

- chart/Chart.yaml
- chart/templates/connection-secret-job.yaml
> chart: recreate promscale connection job on upgrades

- chart/Chart.yaml
- chart/dashboards/postgres-details.json
- chart/values.yaml
Adding a more informative postgres dashboard. The aim is to move this dashboard content into the postgres mixin after a round of tests.
- fixes #619
I am adding this now as we need it ASAP.
> chart/dashboards: add experimental detailed postgres dashboard

- chart/Chart.yaml
- chart/templates/NOTES.txt
Fix typo in notes where we reference the incorrect variable.
- fixes #
> fix typo in notes

- chart/Chart.yaml
- chart/templates/timescaledb-extensions.yaml
- chart/values.yaml
This PR enables postgres extensions which allow easier debugging of the DB.
- fixes #
> chart: enable important postgres extensions to allow more visibility into DB

- chart/Chart.yaml
- chart/values.yaml
This should remove log message about Service object not being able to be created by patroni.
- fixes #
> chart: bump tsdb image version to bugfix patroni

- chart/Chart.yaml
- chart/values.yaml
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
- fixes #
> Enable Prometheus remote write dashboard

- chart/Chart.yaml
- chart/dashboards/promscale.json
Propagating dashboard from https://github.com/timescale/promscale/pull/1747
- fixes #
> chart/dashboards: sync promscale dashboard

- chart/Chart.yaml
- chart/values.yaml
Enable shared memory to prevent issue of "no space left on device". More in https://iobeam.slack.com/archives/C048BDG6EH0/p1668633952456849
- fixes #
> chart: enable shared memory by default

- chart/Chart.yaml
- chart/values.yaml
Disabling collecting database size statistics as this can be expensive and some of this data is also provided via node_exporter.
- fixes #652
> chart: disable collecting database size metric

- chart/Chart.yaml
- chart/values.yaml
With default scrape frequency of 1m, some dashboards show "no data". This is because dashboard queries use `$__rate_interval` which is dynamically calculated and tuned towards higher scrape frequencies.
Additionally by specifying scrape interval we can get more granular data.
- fixes https://github.com/timescale/sre-monitoring/issues/118
> increase node-exporter scrape frequency to allow better data visualization

- chart/Chart.yaml
- chart/dashboards/promscale.json
Propagating https://github.com/timescale/promscale/pull/1773 and https://github.com/timescale/promscale/pull/1772.
Blocked by https://github.com/timescale/helm-charts/pull/508
- fixes #
> synchronize promscale mixin

- README.md
> Add note about Tobs being discontinued
